# Generated by Django 3.1.4 on 2021-04-27 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district_lookup',
            fields=[
                ('jcr_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('field_1', models.FloatField(blank=True, db_column='day_1', null=True)),
                ('field_2', models.FloatField(blank=True, db_column='day_2', null=True)),
                ('field_3', models.FloatField(blank=True, db_column='day_3', null=True)),
                ('field_4', models.FloatField(blank=True, db_column='day_4', null=True)),
                ('field_5', models.FloatField(blank=True, db_column='day_5', null=True)),
                ('field_6', models.FloatField(blank=True, db_column='day_6', null=True)),
                ('field_7', models.FloatField(blank=True, db_column='day_7', null=True)),
                ('field_8', models.FloatField(blank=True, db_column='day_8', null=True)),
                ('field_9', models.FloatField(blank=True, db_column='day_9', null=True)),
                ('field_10', models.FloatField(blank=True, db_column='day_10', null=True)),
                ('field_11', models.FloatField(blank=True, db_column='day_11', null=True)),
                ('field_12', models.FloatField(blank=True, db_column='day_12', null=True)),
                ('field_13', models.FloatField(blank=True, db_column='day_13', null=True)),
                ('field_14', models.FloatField(blank=True, db_column='day_14', null=True)),
                ('field_15', models.FloatField(blank=True, db_column='day_15', null=True)),
                ('field_16', models.FloatField(blank=True, db_column='day_16', null=True)),
                ('field_17', models.FloatField(blank=True, db_column='day_17', null=True)),
                ('field_18', models.FloatField(blank=True, db_column='day_18', null=True)),
                ('field_19', models.FloatField(blank=True, db_column='day_19', null=True)),
                ('field_20', models.FloatField(blank=True, db_column='day_20', null=True)),
                ('field_21', models.FloatField(blank=True, db_column='day_21', null=True)),
                ('field_22', models.FloatField(blank=True, db_column='day_22', null=True)),
                ('field_23', models.FloatField(blank=True, db_column='day_23', null=True)),
                ('field_24', models.FloatField(blank=True, db_column='day_24', null=True)),
                ('field_25', models.FloatField(blank=True, db_column='day_25', null=True)),
                ('field_26', models.FloatField(blank=True, db_column='day_26', null=True)),
                ('field_27', models.FloatField(blank=True, db_column='day_27', null=True)),
                ('field_28', models.FloatField(blank=True, db_column='day_28', null=True)),
                ('field_29', models.FloatField(blank=True, db_column='day_29', null=True)),
                ('field_30', models.FloatField(blank=True, db_column='day_30', null=True)),
                ('hatch_fac', models.FloatField(blank=True, null=True)),
                ('sedan_fac', models.FloatField(blank=True, null=True)),
                ('suv_fac', models.FloatField(blank=True, null=True)),
                ('two_wheel_fac', models.FloatField(blank=True, null=True)),
                ('three_wheel_fac', models.FloatField(blank=True, null=True)),
                ('pedest_fac', models.FloatField(blank=True, null=True)),
                ('bus_fac', models.FloatField(blank=True, null=True)),
                ('truck_fac', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='npr_calculation',
            fields=[
                ('jcr_id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, db_column='Days', null=True)),
                ('maid_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='unique_district',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_attributes',
            fields=[
                ('jcr_id', models.AutoField(primary_key=True, serialize=False)),
                ('maid_count', models.IntegerField(blank=True, null=True)),
                ('male_count', models.IntegerField(blank=True, null=True)),
                ('female_count', models.IntegerField(blank=True, null=True)),
                ('aff_high_count', models.IntegerField(blank=True, null=True)),
                ('aff_medium_count', models.IntegerField(blank=True, null=True)),
                ('aff_low_count', models.IntegerField(blank=True, null=True)),
                ('mean_maid_count', models.IntegerField(blank=True, null=True)),
                ('std_maid_count', models.IntegerField(blank=True, null=True)),
                ('peak_npeak_count', models.IntegerField(blank=True, null=True)),
                ('mean_weekday_sum', models.FloatField(blank=True, null=True)),
                ('wkday_pedestrian', models.IntegerField(blank=True, null=True)),
                ('wkday_vehicle_count', models.IntegerField(blank=True, null=True)),
                ('wkday_sum', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('perdestrian_fac', models.FloatField(blank=True, null=True)),
                ('hatch_fac', models.FloatField(blank=True, null=True)),
                ('suv_fac', models.FloatField(blank=True, null=True)),
                ('sedan_fac', models.FloatField(blank=True, null=True)),
                ('two_wheel_fac', models.FloatField(blank=True, null=True)),
                ('three_wheel_fac', models.FloatField(blank=True, null=True)),
                ('bus_fac', models.FloatField(blank=True, null=True)),
                ('truck_fac', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='traffic_data.unique_district')),
            ],
        ),
        migrations.CreateModel(
            name='cities_cluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maid_count', models.IntegerField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('c_latitude', models.FloatField(blank=True, null=True)),
                ('c_longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('hours', models.TimeField(blank=True, null=True)),
                ('cluster_group', models.IntegerField(blank=True, null=True)),
                ('district_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='traffic_data.unique_district')),
            ],
        ),
    ]
